/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */

import type * as PrismaClient from ".prisma/client"
import type { Context } from "./context"
import type { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    date<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "DateTime";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    date<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "DateTime";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  ChannelInfoWhereUniqueInput: { // input type
    id?: string | null; // String
    uniqueUserChannelPair?: string | null; // String
  }
  FileWhereUniqueInput: { // input type
    Key?: string | null; // String
    id?: string | null; // String
  }
  NotificationWhereUniqueInput: { // input type
    id?: string | null; // String
  }
  ReplyMessageWhereUniqueInput: { // input type
    id?: string | null; // String
  }
  UserWhereUniqueInput: { // input type
    email?: string | null; // String
    id?: string | null; // String
    username?: string | null; // String
  }
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
  Upload: any
}

export interface NexusGenObjects {
  AuthPayload: { // root type
    token: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  Channel: PrismaClient.Channel;
  ChannelInfo: PrismaClient.ChannelInfo;
  Community: PrismaClient.Community;
  File: PrismaClient.File;
  Message: PrismaClient.Message;
  Notification: PrismaClient.Notification;
  OnlinePayload: { // root type
    id: string; // String!
    isOnline: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  Query: {};
  Reaction: PrismaClient.Reaction;
  RemoteAttachment: PrismaClient.RemoteAttachment;
  ReplyMessage: PrismaClient.ReplyMessage;
  Role: PrismaClient.Role;
  TwitterPayload: { // root type
    bio: string; // String!
    followers: string; // String!
    followings: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  TypingStatus: { // root type
    isTyping: boolean; // Boolean!
    username: string; // String!
  }
  UnreadMessagePayload: { // root type
    fromNewUser: boolean; // Boolean!
    messages: NexusGenRootTypes['Message'][]; // [Message!]!
    user: NexusGenRootTypes['User']; // User!
  }
  User: PrismaClient.User;
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  AuthPayload: { // field return type
    token: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  Channel: { // field return type
    author: NexusGenRootTypes['User'] | null; // User
    community: NexusGenRootTypes['Community']; // Community!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    description: string | null; // String
    id: string; // String!
    isPrivate: boolean; // Boolean!
    messages: NexusGenRootTypes['Message'][]; // [Message!]!
    name: string; // String!
    notifications: NexusGenRootTypes['Notification'][]; // [Notification!]!
    typingUsers: NexusGenRootTypes['User'][]; // [User!]!
    url: string; // String!
    userData: NexusGenRootTypes['ChannelInfo'][]; // [ChannelInfo!]!
  }
  ChannelInfo: { // field return type
    channel: NexusGenRootTypes['Channel']; // Channel!
    id: string; // String!
    lastUpdateAt: NexusGenScalars['DateTime']; // DateTime!
    uniqueUserChannelPair: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  Community: { // field return type
    author: NexusGenRootTypes['User'] | null; // User
    channels: NexusGenRootTypes['Channel'][]; // [Channel!]!
    description: string | null; // String
    id: string; // String!
    image: string | null; // String
    isPrivate: boolean; // Boolean!
    members: NexusGenRootTypes['User'][]; // [User!]!
    name: string; // String!
    notifications: NexusGenRootTypes['Notification'][]; // [Notification!]!
    url: string; // String!
  }
  File: { // field return type
    Key: string; // String!
    encoding: string; // String!
    filename: string; // String!
    filesize: string | null; // String
    id: string; // String!
    message: NexusGenRootTypes['Message'] | null; // Message
    mimetype: string; // String!
    uploader: NexusGenRootTypes['User']; // User!
  }
  Message: { // field return type
    attachments: NexusGenRootTypes['File'][]; // [File!]!
    author: NexusGenRootTypes['User']; // User!
    body: string | null; // String
    channel: NexusGenRootTypes['Channel'] | null; // Channel
    children: NexusGenRootTypes['ReplyMessage'][]; // [ReplyMessage!]!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: string; // String!
    reactions: NexusGenRootTypes['Reaction'][]; // [Reaction!]!
    remoteAttachments: NexusGenRootTypes['RemoteAttachment'][]; // [RemoteAttachment!]!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  Notification: { // field return type
    action: string | null; // String
    body: string | null; // String
    channel: NexusGenRootTypes['Channel'] | null; // Channel
    community: NexusGenRootTypes['Community'] | null; // Community
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: string; // String!
    isRead: boolean; // Boolean!
    message: NexusGenRootTypes['Message'] | null; // Message
    receiver: NexusGenRootTypes['User']; // User!
    sender: NexusGenRootTypes['User']; // User!
    type: string | null; // String
  }
  OnlinePayload: { // field return type
    id: string; // String!
    isOnline: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  Query: { // field return type
    allMessages: NexusGenRootTypes['Message'] | null; // Message
    channel: NexusGenRootTypes['Channel'] | null; // Channel
    channelNotifications: NexusGenRootTypes['Notification'] | null; // Notification
    channels: NexusGenRootTypes['Channel'] | null; // Channel
    communities: NexusGenRootTypes['Community'] | null; // Community
    community: NexusGenRootTypes['Community'] | null; // Community
    communityNotifications: NexusGenRootTypes['Notification'] | null; // Notification
    files: NexusGenRootTypes['File'] | null; // File
    getLastMessages: NexusGenRootTypes['Message'] | null; // Message
    getNextMessages: NexusGenRootTypes['Message'] | null; // Message
    getPrevMessages: NexusGenRootTypes['Message'] | null; // Message
    getUnreadMessagesCount: NexusGenRootTypes['UnreadMessagePayload'] | null; // UnreadMessagePayload
    getUser: NexusGenRootTypes['TwitterPayload'] | null; // TwitterPayload
    me: NexusGenRootTypes['User'] | null; // User
    messageReplies: NexusGenRootTypes['ReplyMessage'] | null; // ReplyMessage
    notifications: NexusGenRootTypes['Notification'] | null; // Notification
    privateChannels: NexusGenRootTypes['Channel'] | null; // Channel
    reactions: NexusGenRootTypes['Reaction'] | null; // Reaction
    replyMessages: NexusGenRootTypes['Message'] | null; // Message
    roles: NexusGenRootTypes['Role'] | null; // Role
    searchCommunities: NexusGenRootTypes['Community'] | null; // Community
    searchMessages: NexusGenRootTypes['Message'] | null; // Message
    unreadNotifications: NexusGenRootTypes['Notification'] | null; // Notification
    userFiles: NexusGenRootTypes['File'] | null; // File
    users: NexusGenRootTypes['User'] | null; // User
  }
  Reaction: { // field return type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: string; // String!
    message: NexusGenRootTypes['Message']; // Message!
    name: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
    users: NexusGenRootTypes['User'][]; // [User!]!
  }
  RemoteAttachment: { // field return type
    description: string | null; // String
    id: string; // String!
    parentMessage: NexusGenRootTypes['Message'] | null; // Message
    parentReplyMessage: NexusGenRootTypes['ReplyMessage'] | null; // ReplyMessage
    preview: string | null; // String
    siteName: string | null; // String
    title: string; // String!
    url: string; // String!
    videoLink: string | null; // String
  }
  ReplyMessage: { // field return type
    attachments: NexusGenRootTypes['File'][]; // [File!]!
    author: NexusGenRootTypes['User']; // User!
    body: string; // String!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: string; // String!
    parent: NexusGenRootTypes['Message']; // Message!
    remoteAttachments: NexusGenRootTypes['RemoteAttachment'][]; // [RemoteAttachment!]!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  Role: { // field return type
    color: string; // String!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: string; // String!
    roleSettings: string; // String!
    title: string; // String!
    users: NexusGenRootTypes['User'][]; // [User!]!
  }
  TwitterPayload: { // field return type
    bio: string; // String!
    followers: string; // String!
    followings: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  TypingStatus: { // field return type
    isTyping: boolean; // Boolean!
    username: string; // String!
  }
  UnreadMessagePayload: { // field return type
    fromNewUser: boolean; // Boolean!
    messages: NexusGenRootTypes['Message'][]; // [Message!]!
    user: NexusGenRootTypes['User']; // User!
  }
  User: { // field return type
    bio: string | null; // String
    channelsInfo: NexusGenRootTypes['ChannelInfo'][]; // [ChannelInfo!]!
    communitiesFollowed: NexusGenRootTypes['Community'][]; // [Community!]!
    communitiesOwned: NexusGenRootTypes['Community'][]; // [Community!]!
    currentChannel: NexusGenRootTypes['Channel'] | null; // Channel
    email: string | null; // String
    files: NexusGenRootTypes['File'][]; // [File!]!
    fullname: string; // String!
    id: string; // String!
    image: string | null; // String
    isOnline: boolean; // Boolean!
    messages: NexusGenRootTypes['Message'][]; // [Message!]!
    notificationsReceived: NexusGenRootTypes['Notification'][]; // [Notification!]!
    notificationsSend: NexusGenRootTypes['Notification'][]; // [Notification!]!
    owner: string | null; // String
    password: string | null; // String
    reactions: NexusGenRootTypes['Reaction'][]; // [Reaction!]!
    replyMessages: NexusGenRootTypes['ReplyMessage'][]; // [ReplyMessage!]!
    role: NexusGenRootTypes['Role'][]; // [Role!]!
    social: string | null; // String
    username: string; // String!
  }
}

export interface NexusGenFieldTypeNames {
  AuthPayload: { // field return type name
    token: 'String'
    user: 'User'
  }
  Channel: { // field return type name
    author: 'User'
    community: 'Community'
    createdAt: 'DateTime'
    description: 'String'
    id: 'String'
    isPrivate: 'Boolean'
    messages: 'Message'
    name: 'String'
    notifications: 'Notification'
    typingUsers: 'User'
    url: 'String'
    userData: 'ChannelInfo'
  }
  ChannelInfo: { // field return type name
    channel: 'Channel'
    id: 'String'
    lastUpdateAt: 'DateTime'
    uniqueUserChannelPair: 'String'
    user: 'User'
  }
  Community: { // field return type name
    author: 'User'
    channels: 'Channel'
    description: 'String'
    id: 'String'
    image: 'String'
    isPrivate: 'Boolean'
    members: 'User'
    name: 'String'
    notifications: 'Notification'
    url: 'String'
  }
  File: { // field return type name
    Key: 'String'
    encoding: 'String'
    filename: 'String'
    filesize: 'String'
    id: 'String'
    message: 'Message'
    mimetype: 'String'
    uploader: 'User'
  }
  Message: { // field return type name
    attachments: 'File'
    author: 'User'
    body: 'String'
    channel: 'Channel'
    children: 'ReplyMessage'
    createdAt: 'DateTime'
    id: 'String'
    reactions: 'Reaction'
    remoteAttachments: 'RemoteAttachment'
    updatedAt: 'DateTime'
  }
  Notification: { // field return type name
    action: 'String'
    body: 'String'
    channel: 'Channel'
    community: 'Community'
    createdAt: 'DateTime'
    id: 'String'
    isRead: 'Boolean'
    message: 'Message'
    receiver: 'User'
    sender: 'User'
    type: 'String'
  }
  OnlinePayload: { // field return type name
    id: 'String'
    isOnline: 'String'
    user: 'User'
  }
  Query: { // field return type name
    allMessages: 'Message'
    channel: 'Channel'
    channelNotifications: 'Notification'
    channels: 'Channel'
    communities: 'Community'
    community: 'Community'
    communityNotifications: 'Notification'
    files: 'File'
    getLastMessages: 'Message'
    getNextMessages: 'Message'
    getPrevMessages: 'Message'
    getUnreadMessagesCount: 'UnreadMessagePayload'
    getUser: 'TwitterPayload'
    me: 'User'
    messageReplies: 'ReplyMessage'
    notifications: 'Notification'
    privateChannels: 'Channel'
    reactions: 'Reaction'
    replyMessages: 'Message'
    roles: 'Role'
    searchCommunities: 'Community'
    searchMessages: 'Message'
    unreadNotifications: 'Notification'
    userFiles: 'File'
    users: 'User'
  }
  Reaction: { // field return type name
    createdAt: 'DateTime'
    id: 'String'
    message: 'Message'
    name: 'String'
    updatedAt: 'DateTime'
    users: 'User'
  }
  RemoteAttachment: { // field return type name
    description: 'String'
    id: 'String'
    parentMessage: 'Message'
    parentReplyMessage: 'ReplyMessage'
    preview: 'String'
    siteName: 'String'
    title: 'String'
    url: 'String'
    videoLink: 'String'
  }
  ReplyMessage: { // field return type name
    attachments: 'File'
    author: 'User'
    body: 'String'
    createdAt: 'DateTime'
    id: 'String'
    parent: 'Message'
    remoteAttachments: 'RemoteAttachment'
    updatedAt: 'DateTime'
  }
  Role: { // field return type name
    color: 'String'
    createdAt: 'DateTime'
    id: 'String'
    roleSettings: 'String'
    title: 'String'
    users: 'User'
  }
  TwitterPayload: { // field return type name
    bio: 'String'
    followers: 'String'
    followings: 'String'
    user: 'User'
  }
  TypingStatus: { // field return type name
    isTyping: 'Boolean'
    username: 'String'
  }
  UnreadMessagePayload: { // field return type name
    fromNewUser: 'Boolean'
    messages: 'Message'
    user: 'User'
  }
  User: { // field return type name
    bio: 'String'
    channelsInfo: 'ChannelInfo'
    communitiesFollowed: 'Community'
    communitiesOwned: 'Community'
    currentChannel: 'Channel'
    email: 'String'
    files: 'File'
    fullname: 'String'
    id: 'String'
    image: 'String'
    isOnline: 'Boolean'
    messages: 'Message'
    notificationsReceived: 'Notification'
    notificationsSend: 'Notification'
    owner: 'String'
    password: 'String'
    reactions: 'Reaction'
    replyMessages: 'ReplyMessage'
    role: 'Role'
    social: 'String'
    username: 'String'
  }
}

export interface NexusGenArgTypes {
  Channel: {
    typingUsers: { // args
      after?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
      before?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      skip?: number | null; // Int
    }
    userData: { // args
      after?: NexusGenInputs['ChannelInfoWhereUniqueInput'] | null; // ChannelInfoWhereUniqueInput
      before?: NexusGenInputs['ChannelInfoWhereUniqueInput'] | null; // ChannelInfoWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      skip?: number | null; // Int
    }
  }
  Query: {
    allMessages: { // args
      channelUrl?: string | null; // String
    }
    channel: { // args
      url?: string | null; // String
    }
    channelNotifications: { // args
      channelUrl?: string | null; // String
    }
    channels: { // args
      communityUrl?: string | null; // String
    }
    community: { // args
      id?: string | null; // ID
      url?: string | null; // String
    }
    communityNotifications: { // args
      communityUrl?: string | null; // String
    }
    files: { // args
      after?: string | null; // ID
    }
    getLastMessages: { // args
      channelUrl?: string | null; // String
      cursorId?: string | null; // ID
      lastVisitDate?: string | null; // String
      number?: string | null; // String
    }
    getNextMessages: { // args
      channelUrl?: string | null; // String
      cursorId?: string | null; // ID
      number?: string | null; // String
    }
    getPrevMessages: { // args
      channelUrl?: string | null; // String
      cursorId?: string | null; // ID
      number?: string | null; // String
    }
    getUnreadMessagesCount: { // args
      channelUrl?: string | null; // String
      username?: string | null; // String
    }
    getUser: { // args
      username: string; // String!
    }
    messageReplies: { // args
      after?: string | null; // ID
      messageId?: string | null; // String
    }
    reactions: { // args
      messageId?: string | null; // String
    }
    replyMessages: { // args
      after?: string | null; // ID
      channelUrl?: string | null; // String
    }
    searchCommunities: { // args
      searchString?: string | null; // String
    }
    searchMessages: { // args
      channelUrl?: string | null; // String
      searchQuery?: string | null; // String
    }
    userFiles: { // args
      after?: string | null; // ID
      userId?: string | null; // ID
    }
    users: { // args
      searchString?: string | null; // String
    }
  }
  ReplyMessage: {
    attachments: { // args
      after?: NexusGenInputs['FileWhereUniqueInput'] | null; // FileWhereUniqueInput
      before?: NexusGenInputs['FileWhereUniqueInput'] | null; // FileWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      skip?: number | null; // Int
    }
  }
  Role: {
    users: { // args
      after?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
      before?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      skip?: number | null; // Int
    }
  }
  User: {
    notificationsReceived: { // args
      after?: NexusGenInputs['NotificationWhereUniqueInput'] | null; // NotificationWhereUniqueInput
      before?: NexusGenInputs['NotificationWhereUniqueInput'] | null; // NotificationWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      skip?: number | null; // Int
    }
    notificationsSend: { // args
      after?: NexusGenInputs['NotificationWhereUniqueInput'] | null; // NotificationWhereUniqueInput
      before?: NexusGenInputs['NotificationWhereUniqueInput'] | null; // NotificationWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      skip?: number | null; // Int
    }
    replyMessages: { // args
      after?: NexusGenInputs['ReplyMessageWhereUniqueInput'] | null; // ReplyMessageWhereUniqueInput
      before?: NexusGenInputs['ReplyMessageWhereUniqueInput'] | null; // ReplyMessageWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      skip?: number | null; // Int
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
    /**
     * The nullability guard can be helpful, but is also a potentially expensive operation for lists.
     * We need to iterate the entire list to check for null items to guard against. Set this to true
     * to skip the null guard on a specific field if you know there's no potential for unsafe types.
     */
    skipNullGuard?: boolean
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}